version: '3.3'
networks:
    myNetwork:
        external:
            name: myNetwork
services:
    ca_org1:
        deploy:
            replicas: 1
            restart_policy: 
                condition: any
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == egs01_ubuntu1804_hyperledger
        image: hyperledger/fabric-ca:1.4
        hostname: ca.org1.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org1.exapmle.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b32619c5dd78ed431227ce43a9434806278fc8836edc58eba757784799ead206_sk
        ports:
            - "7054:7054"
        command: fabric-ca-server start -b admin:adminpw -d
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            myNetwork: 
                aliases:
                    - ca.org1.example.com

    peer0_org1:
        deploy:
            replicas: 1
            restart_policy: 
                condition: any
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == egs01_ubuntu1804_hyperledger
        image: hyperledger/fabric-peer:1.4
        hostname: peer0.org1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=myNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=myNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp

            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org1.example.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=sa
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234

            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
            - 7051:7051
            - 7053:7053
        networks:
            myNetwork: 
                aliases:
                    - peer0.org1.example.com

    couchdb_peer0_org1:
        image: hyperledger/fabric-couchdb:0.4.14
        deploy:
            replicas: 1
            restart_policy: 
                condition: any
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == egs01_ubuntu1804_hyperledger
        hostname: couchdb.peer0.org1.example.com            
        environment:
            - COUCHDB_USER=sa
            - COUCHDB_PASSWORD=1234
        volumes:
            - /var/mydb/couchdb1/:/opt/couchdb/data
        ports:
            - 5984:5984    
        networks:
            myNetwork: 
                aliases:
                    - couchdb.peer0.org1.example.com               
    
    cli:
        deploy:
            replicas: 1
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == egs01_ubuntu1804_hyperledger
        image: hyperledger/fabric-tools:1.4
        tty: true
        hostname: cli
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_ID=cli.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_CHAINCODE_KEEPALIVE=10
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/chaincode:/opt/gopath/src/github.com/chaincode
            - /var/mynetwork/fabric-src/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
            - /var/mynetwork/certs/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - /var/mynetwork/certs/config:/var/hyperledger/config
            - /var/mynetwork/bin/:/var/bin
        networks:
            - myNetwork

        api:
            deploy:
                replicas: 1
                restart_policy: 
                    condition: on-failure
                    delay: 5s
                    max_attempts: 3
                placement: 
                    constraints: 
                        - node.hostname == egs01_ubuntu1804_hyperledger
            image: apiserver:0.0.1
            tty: true
            hostname: apiserver
            volumes:
                 - /var/mynetwork/network/
            networks:
                - myNetwork
